from .project import Project
from .localization_general import LocalizationGeneral
from .localization import Localization
from .requirements import Requirement
from .requirements_general import RequirementsGeneral
from .participants_general import ParticipantsGeneral
from .participants import Participants
from .objectives import Objectives
from .objectives_indicators import ObjectivesIndicator
from .objectives_causes import ObjectivesCauses
from .alternatives_general import AlternativesGeneral
from .alternatives import Alternatives
from .population import Population
from .affected_population import AffectedPopulation
from .intervention_population import InterventionPopulation
from .characteristics_population import CharacteristicsPopulation
from .technical_analysis import TechnicalAnalysis