"""Add development_plan model

Revision ID: 24d50f9cad37
Revises: 19451e1499a6
Create Date: 2026-03-14 10:21:30.516661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '24d50f9cad37'
down_revision: Union[str, Sequence[str], None] = '19451e1499a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('development_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program', sa.String(), nullable=True),
    sa.Column('national_development_plan', sa.String(), nullable=True),
    sa.Column('departmental_or_sectoral_development_plan', sa.String(), nullable=True),
    sa.Column('strategy_departmental', sa.String(), nullable=True),
    sa.Column('program_departmental', sa.String(), nullable=True),
    sa.Column('district_or_municipal_development_plan', sa.String(), nullable=True),
    sa.Column('strategy_district', sa.String(), nullable=True),
    sa.Column('program_district', sa.String(), nullable=True),
    sa.Column('community_type', sa.String(), nullable=True),
    sa.Column('ethnic_group_planning_instruments', sa.String(), nullable=True),
    sa.Column('other_development_plan', sa.String(), nullable=True),
    sa.Column('strategy_other', sa.String(), nullable=True),
    sa.Column('program_other', sa.String(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_index(op.f('ix_development_plans_id'), 'development_plans', ['id'], unique=False)
    op.drop_index(op.f('idx_chat_history__session_id'), table_name='chat_history_')
    op.drop_table('chat_history_')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_history_',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('message', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_history__pkey'))
    )
    op.create_index(op.f('idx_chat_history__session_id'), 'chat_history_', ['session_id'], unique=False)
    op.drop_index(op.f('ix_development_plans_id'), table_name='development_plans')
    op.drop_table('development_plans')
    # ### end Alembic commands ###
