"""remove name column from products

Revision ID: c19a024610f3
Revises: a7f3c2b8e911
Create Date: 2026-05-26 18:05:20.846589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'c19a024610f3'
down_revision: Union[str, Sequence[str], None] = 'a7f3c2b8e911'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alternatives', 'alternative_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('products', sa.Column('name', sa.String(), nullable=True))
    op.drop_column('projects', 'municipality')
    op.drop_column('projects', 'region')
    op.drop_column('projects', 'department')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('department', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('region', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('projects', sa.Column('municipality', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('products', 'name')
    op.alter_column('alternatives', 'alternative_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
