"""agregar nuevos campos a project

Revision ID: c3bcc6e2df7c
Revises: d1983286d509
Create Date: 2026-03-16 22:06:40.415198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c3bcc6e2df7c'
down_revision: Union[str, Sequence[str], None] = 'd1983286d509'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_chat_history__session_id'), table_name='chat_history_')
    op.drop_table('chat_history_')
    op.add_column('projects', sa.Column('process', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('object_desc', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('region', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('department', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('municipality', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('intervention_type', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('project_typology', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('main_product', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('sector', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'sector')
    op.drop_column('projects', 'main_product')
    op.drop_column('projects', 'project_typology')
    op.drop_column('projects', 'intervention_type')
    op.drop_column('projects', 'municipality')
    op.drop_column('projects', 'department')
    op.drop_column('projects', 'region')
    op.drop_column('projects', 'object_desc')
    op.drop_column('projects', 'process')
    op.create_table('chat_history_',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('message', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_history__pkey'))
    )
    op.create_index(op.f('idx_chat_history__session_id'), 'chat_history_', ['session_id'], unique=False)
    # ### end Alembic commands ###
