"""Add pnd model

Revision ID: d1983286d509
Revises: 24d50f9cad37
Create Date: 2026-03-14 11:16:24.575105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd1983286d509'
down_revision: Union[str, Sequence[str], None] = '24d50f9cad37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pnds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transformation', sa.String(), nullable=True),
    sa.Column('pillar', sa.String(), nullable=True),
    sa.Column('catalyst', sa.String(), nullable=True),
    sa.Column('component', sa.String(), nullable=True),
    sa.Column('development_plan_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['development_plan_id'], ['development_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pnds_id'), 'pnds', ['id'], unique=False)
    op.drop_index(op.f('idx_chat_history__session_id'), table_name='chat_history_')
    op.drop_table('chat_history_')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_history_',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('message', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_history__pkey'))
    )
    op.create_index(op.f('idx_chat_history__session_id'), 'chat_history_', ['session_id'], unique=False)
    op.drop_index(op.f('ix_pnds_id'), table_name='pnds')
    op.drop_table('pnds')
    # ### end Alembic commands ###
