"""initial schema

Revision ID: ffe44517c125
Revises: 
Create Date: 2026-02-28 12:23:02.802323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffe44517c125'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_table('alternatives_general',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solution_alternatives', sa.Boolean(), nullable=False),
    sa.Column('cost', sa.Boolean(), nullable=False),
    sa.Column('profitability', sa.Boolean(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_index(op.f('ix_alternatives_general_id'), 'alternatives_general', ['id'], unique=False)
    op.create_table('localization_general',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('administrative_political_factors', sa.Boolean(), nullable=True),
    sa.Column('proximity_to_target_population', sa.Boolean(), nullable=True),
    sa.Column('proximity_to_supply_sources', sa.Boolean(), nullable=True),
    sa.Column('communications', sa.Boolean(), nullable=True),
    sa.Column('land_cost_and_availability', sa.Boolean(), nullable=True),
    sa.Column('public_services_availability', sa.Boolean(), nullable=True),
    sa.Column('labor_availability_and_cost', sa.Boolean(), nullable=True),
    sa.Column('tax_and_legal_structure', sa.Boolean(), nullable=True),
    sa.Column('environmental_factors', sa.Boolean(), nullable=True),
    sa.Column('gender_equity_impact', sa.Boolean(), nullable=True),
    sa.Column('transport_means_and_costs', sa.Boolean(), nullable=True),
    sa.Column('public_order', sa.Boolean(), nullable=True),
    sa.Column('other_factors', sa.Boolean(), nullable=True),
    sa.Column('topography', sa.Boolean(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_index(op.f('ix_localization_general_id'), 'localization_general', ['id'], unique=False)
    op.create_table('objectives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('general_problem', sa.Text(), nullable=False),
    sa.Column('general_objective', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_index(op.f('ix_objectives_id'), 'objectives', ['id'], unique=False)
    op.create_table('participants_general',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participants_analisis', sa.Text(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('participants_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_index(op.f('ix_participants_general_id'), 'participants_general', ['id'], unique=False)
    op.create_table('population',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('population_type_affected', sa.Text(), nullable=True),
    sa.Column('number_affected', sa.Integer(), nullable=True),
    sa.Column('source_information_affected', sa.Text(), nullable=True),
    sa.Column('population_type_intervention', sa.Text(), nullable=False),
    sa.Column('number_intervention', sa.Integer(), nullable=False),
    sa.Column('source_information_intervention', sa.Text(), nullable=True),
    sa.Column('population_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_index(op.f('ix_population_id'), 'population', ['id'], unique=False)
    op.create_table('problems',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('central_problem', sa.Text(), nullable=False),
    sa.Column('current_description', sa.Text(), nullable=False),
    sa.Column('magnitude_problem', sa.Text(), nullable=False),
    sa.Column('problem_tree_json', sa.JSON(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_index(op.f('ix_problems_id'), 'problems', ['id'], unique=False)
    op.create_table('requirements_general',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requirements_analysis', sa.Text(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_index(op.f('ix_requirements_general_id'), 'requirements_general', ['id'], unique=False)
    op.create_table('technical_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis', sa.Text(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_index(op.f('ix_technical_analysis_id'), 'technical_analysis', ['id'], unique=False)
    op.create_table('affected_population',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region', sa.Text(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('population_center', sa.Text(), nullable=True),
    sa.Column('location_entity', sa.Text(), nullable=True),
    sa.Column('population_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['population_id'], ['population.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affected_population_id'), 'affected_population', ['id'], unique=False)
    op.create_table('alternatives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('alternative_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['alternative_id'], ['alternatives_general.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alternatives_id'), 'alternatives', ['id'], unique=False)
    op.create_table('characteristics_population',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classification', sa.Text(), nullable=False),
    sa.Column('detail', sa.String(), nullable=False),
    sa.Column('people_number', sa.Integer(), nullable=False),
    sa.Column('information', sa.Text(), nullable=True),
    sa.Column('population_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['population_id'], ['population.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characteristics_population_id'), 'characteristics_population', ['id'], unique=False)
    op.create_table('direct_causes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_direct_causes_id'), 'direct_causes', ['id'], unique=False)
    op.create_table('direct_effects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_direct_effects_id'), 'direct_effects', ['id'], unique=False)
    op.create_table('intervention_population',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region', sa.Text(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('population_center', sa.Text(), nullable=True),
    sa.Column('location_entity', sa.Text(), nullable=True),
    sa.Column('population_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['population_id'], ['population.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intervention_population_id'), 'intervention_population', ['id'], unique=False)
    op.create_table('localization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('department', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('type_group', sa.Text(), nullable=True),
    sa.Column('group', sa.Text(), nullable=True),
    sa.Column('entity', sa.Text(), nullable=True),
    sa.Column('georeferencing', sa.Boolean(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('localization_general_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['localization_general_id'], ['localization_general.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('objectives_causes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('cause_related', sa.Text(), nullable=True),
    sa.Column('specifics_objectives', sa.Text(), nullable=True),
    sa.Column('objective_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['objective_id'], ['objectives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_objectives_causes_id'), 'objectives_causes', ['id'], unique=False)
    op.create_table('objectives_indicator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indicator', sa.Text(), nullable=False),
    sa.Column('unit', sa.Text(), nullable=False),
    sa.Column('meta', sa.Float(), nullable=False),
    sa.Column('source_type', sa.Text(), nullable=False),
    sa.Column('source_validation', sa.Text(), nullable=False),
    sa.Column('objective_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['objective_id'], ['objectives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_objectives_indicator_id'), 'objectives_indicator', ['id'], unique=False)
    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_actor', sa.Text(), nullable=True),
    sa.Column('participant_entity', sa.Text(), nullable=True),
    sa.Column('interest_expectative', sa.Text(), nullable=True),
    sa.Column('rol', sa.Text(), nullable=True),
    sa.Column('contribution_conflicts', sa.Text(), nullable=True),
    sa.Column('participants_general_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['participants_general_id'], ['participants_general.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('good_service_name', sa.Text(), nullable=True),
    sa.Column('good_service_description', sa.Text(), nullable=True),
    sa.Column('supply_description', sa.Text(), nullable=True),
    sa.Column('demand_description', sa.Text(), nullable=True),
    sa.Column('unit_of_measure', sa.Text(), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('last_projected_year', sa.Integer(), nullable=True),
    sa.Column('requirements_general_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['requirements_general_id'], ['requirements_general.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('indirect_causes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('direct_cause_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['direct_cause_id'], ['direct_causes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indirect_causes_id'), 'indirect_causes', ['id'], unique=False)
    op.create_table('indirect_effects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('direct_effect_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['direct_effect_id'], ['direct_effects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indirect_effects_id'), 'indirect_effects', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_indirect_effects_id'), table_name='indirect_effects')
    op.drop_table('indirect_effects')
    op.drop_index(op.f('ix_indirect_causes_id'), table_name='indirect_causes')
    op.drop_table('indirect_causes')
    op.drop_table('requirements')
    op.drop_table('participants')
    op.drop_index(op.f('ix_objectives_indicator_id'), table_name='objectives_indicator')
    op.drop_table('objectives_indicator')
    op.drop_index(op.f('ix_objectives_causes_id'), table_name='objectives_causes')
    op.drop_table('objectives_causes')
    op.drop_table('localization')
    op.drop_index(op.f('ix_intervention_population_id'), table_name='intervention_population')
    op.drop_table('intervention_population')
    op.drop_index(op.f('ix_direct_effects_id'), table_name='direct_effects')
    op.drop_table('direct_effects')
    op.drop_index(op.f('ix_direct_causes_id'), table_name='direct_causes')
    op.drop_table('direct_causes')
    op.drop_index(op.f('ix_characteristics_population_id'), table_name='characteristics_population')
    op.drop_table('characteristics_population')
    op.drop_index(op.f('ix_alternatives_id'), table_name='alternatives')
    op.drop_table('alternatives')
    op.drop_index(op.f('ix_affected_population_id'), table_name='affected_population')
    op.drop_table('affected_population')
    op.drop_index(op.f('ix_technical_analysis_id'), table_name='technical_analysis')
    op.drop_table('technical_analysis')
    op.drop_index(op.f('ix_requirements_general_id'), table_name='requirements_general')
    op.drop_table('requirements_general')
    op.drop_index(op.f('ix_problems_id'), table_name='problems')
    op.drop_table('problems')
    op.drop_index(op.f('ix_population_id'), table_name='population')
    op.drop_table('population')
    op.drop_index(op.f('ix_participants_general_id'), table_name='participants_general')
    op.drop_table('participants_general')
    op.drop_index(op.f('ix_objectives_id'), table_name='objectives')
    op.drop_table('objectives')
    op.drop_index(op.f('ix_localization_general_id'), table_name='localization_general')
    op.drop_table('localization_general')
    op.drop_index(op.f('ix_alternatives_general_id'), table_name='alternatives_general')
    op.drop_table('alternatives_general')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
