"""create projects table

Revision ID: c96068dc73f2
Revises: 
Create Date: 2025-10-08 22:54:51.834485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c96068dc73f2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_direct_causes_id'), table_name='direct_causes')
    # op.drop_table('direct_causes')
    # op.drop_index(op.f('ix_participants_general_id'), table_name='participants_general')
    # op.drop_table('participants_general')
    # op.drop_index(op.f('ix_indirect_causes_id'), table_name='indirect_causes')
    # op.drop_table('indirect_causes')
    # op.drop_index(op.f('ix_direct_effects_id'), table_name='direct_effects')
    # op.drop_table('direct_effects')
    # op.drop_index(op.f('ix_alternatives_id'), table_name='alternatives')
    # op.drop_table('alternatives')
    # op.drop_index(op.f('ix_objectives_indicator_id'), table_name='objectives_indicator')
    # op.drop_table('objectives_indicator')
    # op.drop_index(op.f('ix_intervention_population_id'), table_name='intervention_population')
    # op.drop_table('intervention_population')
    # op.drop_table('participants')
    # op.drop_index(op.f('ix_problems_id'), table_name='problems')
    # op.drop_table('problems')
    # op.drop_index(op.f('ix_affected_population_id'), table_name='affected_population')
    # op.drop_table('affected_population')
    # op.drop_index(op.f('ix_population_id'), table_name='population')
    # op.drop_table('population')
    # op.drop_index(op.f('ix_objectives_id'), table_name='objectives')
    # op.drop_table('objectives')
    # op.drop_index(op.f('ix_characteristics_population_id'), table_name='characteristics_population')
    # op.drop_table('characteristics_population')
    # op.drop_index(op.f('ix_projects_id'), table_name='projects')
    # op.drop_index(op.f('ix_projects_name'), table_name='projects')
    # op.drop_table('projects')
    # op.drop_index(op.f('ix_objectives_causes_id'), table_name='objectives_causes')
    # op.drop_table('objectives_causes')
    # op.drop_index(op.f('ix_chat_history_id'), table_name='chat_history')
    # op.drop_table('chat_history')
    # op.drop_index(op.f('ix_alternatives_general_id'), table_name='alternatives_general')
    # op.drop_table('alternatives_general')
    # op.drop_index(op.f('ix_indirect_effects_id'), table_name='indirect_effects')
    # op.drop_table('indirect_effects')
    # op.drop_index(op.f('ix_survey_id'), table_name='survey')
    # op.drop_table('survey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('survey_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('survey_project_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('survey_pkey'))
    )
    op.create_index(op.f('ix_survey_id'), 'survey', ['id'], unique=False)
    op.create_table('indirect_effects',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('direct_effect_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['direct_effect_id'], ['direct_effects.id'], name=op.f('indirect_effects_direct_effect_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('indirect_effects_pkey'))
    )
    op.create_index(op.f('ix_indirect_effects_id'), 'indirect_effects', ['id'], unique=False)
    op.create_table('alternatives_general',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('alternatives_general_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('solution_alternatives', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('cost', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('profitability', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='alternatives_general_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_alternatives_general_id'), 'alternatives_general', ['id'], unique=False)
    op.create_table('chat_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tab', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sender', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('chat_history_project_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_history_pkey'))
    )
    op.create_index(op.f('ix_chat_history_id'), 'chat_history', ['id'], unique=False)
    op.create_table('objectives_causes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cause_related', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('specifics_objectives', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('objective_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['objective_id'], ['objectives.id'], name=op.f('objectives_causes_objective_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('objectives_causes_pkey'))
    )
    op.create_index(op.f('ix_objectives_causes_id'), 'objectives_causes', ['id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('projects_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='projects_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_table('characteristics_population',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('classification', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('detail', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('people_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('information', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('population_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['population_id'], ['population.id'], name=op.f('characteristics_population_population_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('characteristics_population_pkey'))
    )
    op.create_index(op.f('ix_characteristics_population_id'), 'characteristics_population', ['id'], unique=False)
    op.create_table('objectives',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('objectives_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('general_problem', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('general_objective', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='objectives_project_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='objectives_pkey'),
    sa.UniqueConstraint('project_id', name='objectives_project_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_objectives_id'), 'objectives', ['id'], unique=False)
    op.create_table('population',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('population_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('population_type_affected', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('number_affected', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('source_information_affected', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('population_type_intervention', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('number_intervention', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('source_information_intervention', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('population_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='population_project_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='population_pkey'),
    sa.UniqueConstraint('project_id', name='population_project_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_population_id'), 'population', ['id'], unique=False)
    op.create_table('affected_population',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('region', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('department', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('city', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('population_center', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('location_entity', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('population_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['population_id'], ['population.id'], name=op.f('affected_population_population_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('affected_population_pkey'))
    )
    op.create_index(op.f('ix_affected_population_id'), 'affected_population', ['id'], unique=False)
    op.create_table('problems',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('problems_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('central_problem', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('current_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('magnitude_problem', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('problem_tree_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('chat_history', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='problems_project_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='problems_pkey'),
    sa.UniqueConstraint('project_id', name='problems_project_id_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_problems_id'), 'problems', ['id'], unique=False)
    op.create_table('participants',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('participant_actor', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('participant_entity', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('interest_expectative', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rol', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('contribution_conflicts', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('participants_general_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['participants_general_id'], ['participants_general.id'], name=op.f('participants_participants_general_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('participants_pkey'))
    )
    op.create_table('intervention_population',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('region', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('department', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('city', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('population_center', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('location_entity', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('population_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['population_id'], ['population.id'], name=op.f('intervention_population_population_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('intervention_population_pkey'))
    )
    op.create_index(op.f('ix_intervention_population_id'), 'intervention_population', ['id'], unique=False)
    op.create_table('objectives_indicator',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('indicator', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('unit', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('meta', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('source_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('source_validation', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('objective_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['objective_id'], ['objectives.id'], name=op.f('objectives_indicator_objective_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('objectives_indicator_pkey'))
    )
    op.create_index(op.f('ix_objectives_indicator_id'), 'objectives_indicator', ['id'], unique=False)
    op.create_table('alternatives',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('state', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('alternative_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['alternative_id'], ['alternatives_general.id'], name=op.f('alternatives_alternative_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('alternatives_pkey'))
    )
    op.create_index(op.f('ix_alternatives_id'), 'alternatives', ['id'], unique=False)
    op.create_table('direct_effects',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('problem_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('direct_effects_problem_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('direct_effects_pkey'))
    )
    op.create_index(op.f('ix_direct_effects_id'), 'direct_effects', ['id'], unique=False)
    op.create_table('indirect_causes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('direct_cause_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['direct_cause_id'], ['direct_causes.id'], name=op.f('indirect_causes_direct_cause_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('indirect_causes_pkey'))
    )
    op.create_index(op.f('ix_indirect_causes_id'), 'indirect_causes', ['id'], unique=False)
    op.create_table('participants_general',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('participants_analisis', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('participants_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('participants_general_project_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('participants_general_pkey')),
    sa.UniqueConstraint('project_id', name=op.f('participants_general_project_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_participants_general_id'), 'participants_general', ['id'], unique=False)
    op.create_table('direct_causes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('problem_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], name=op.f('direct_causes_problem_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('direct_causes_pkey'))
    )
    op.create_index(op.f('ix_direct_causes_id'), 'direct_causes', ['id'], unique=False)
    # ### end Alembic commands ###
